services:
  - type: web
    name: insurance-claim-fraud-mlops
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit.app/app.py --server.port $PORT --server.address 0.0.0.0
